vim.g.mapleader = " "
vim.keymap.set("n", "<leader>m", ":Oil<CR>")
-- vim.keymap.set("n", "<leader>u", vim.cmd.UndotreeToggle)
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
vim.keymap.set("x", "<leader>p", '"_dP')
vim.keymap.set("n", "<leader>y", '"+y')
vim.keymap.set("v", "<leader>y", '"+y')
vim.keymap.set("n", "<leader>Y", '"+Y')
vim.keymap.set("n", "<leader>G", ":tab Git<CR>")
vim.keymap.set("n", "<leader>w", ":w<CR>")
vim.keymap.set("n", "<leader>l", ":bnext<CR>")
vim.keymap.set("n", "<leader>h", ":bprev<CR>")
vim.keymap.set("i", "<Caps>", "<Esc>")
vim.keymap.set("t", "<Esc>", "<C-\\><C-n>")

-- Dap keybinds
vim.keymap.set("n", "<F5>", function()
	require("dap").continue()
end, { desc = "Dap: continue" })
vim.keymap.set("n", "<F6>", function()
	require("dap").step_over()
end, { desc = "Dap: step over" })
vim.keymap.set("n", "<F7>", function()
	require("dap").step_into()
end, { desc = "Dap: step into" })
vim.keymap.set("n", "<F8>", function()
	require("dap").step_out()
end, { desc = "Dap: step out" })
vim.keymap.set("n", "<Leader>b", function()
	require("dap").toggle_breakpoint()
end, { desc = "Dap: Toggle breakpoint" })
vim.keymap.set({ "n", "v" }, "<Leader>dh", function()
	require("dap.ui.widgets").hover()
end, { desc = "Dap: hover" })
vim.keymap.set({ "n", "v" }, "<Leader>dp", function()
	require("dap.ui.widgets").preview()
end, { desc = "Dap: preview" })
